[CmdletBinding()]
param(
  [Parameter(Mandatory = $true)]
  [string]$InputPath,

  [Parameter(Mandatory = $false)]
  [string]$OutputPath = "PingTool.WinUI3\Assets\oui.csv"
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

function Normalize-OuiPrefix {
  param([string]$Text)

  $hex = -join ($Text.ToCharArray() | Where-Object { $_ -match '[0-9A-Fa-f]' } | ForEach-Object { $_.ToString().ToUpperInvariant() })
  if ($hex.Length -lt 6) { return $null }
  return $hex.Substring(0, 6)
}

if (-not (Test-Path -LiteralPath $InputPath)) {
  throw "Input file not found: $InputPath`n`nTip: If you want to use Wireshark's manuf file, run:`n  Invoke-WebRequest -Uri 'https://www.wireshark.org/download/automated/data/manuf' -OutFile .\manuf`nThen re-run:`n  powershell -ExecutionPolicy Bypass -File .\tools\Import-OuiDataset.ps1 -InputPath .\manuf"
}

$vendors = @{}

# Supports:
# - PingTool oui.csv format: OUI,VENDOR
# - Wireshark manuf: 00:11:22\tVendor Name
# - Generic lines containing a MAC/OUI then vendor text
# - IEEE CSV-like: columns with OUI + organization name (best-effort)

Get-Content -LiteralPath $InputPath -Encoding UTF8 | ForEach-Object {
  $line = ([string]$_).Trim()
  if ($line.Length -eq 0) { return }
  if ($line.StartsWith('#')) { return }

  # Strip inline comments for manuf-style.
  $lineNoComment = $line.Split('#')[0].Trim()
  if ($lineNoComment.Length -eq 0) { return }

  # If CSV with comma, try OUI,VENDOR first.
  if ($lineNoComment.Contains(',')) {
    $parts = $lineNoComment.Split(',', 2)
    if ($parts.Count -eq 2) {
      $prefix = Normalize-OuiPrefix $parts[0]
      $vendor = $parts[1].Trim().Trim('"')
      if ($prefix -and $vendor) {
        $vendors[$prefix] = $vendor
        return
      }
    }
  }

  # Try tab-delimited manuf format.
  if ($lineNoComment.Contains("`t")) {
    $tabParts = $lineNoComment -split "`t+"
    if ($tabParts.Count -ge 2) {
      $prefix = Normalize-OuiPrefix $tabParts[0]
      $vendor = ($tabParts[1..($tabParts.Count-1)] -join " ").Trim()
      if ($prefix -and $vendor) {
        $vendors[$prefix] = $vendor
        return
      }
    }
  }

  # Fallback: first token is OUI/MAC, remainder is vendor.
  $spaceParts = $lineNoComment -split "\s+", 2
  if ($spaceParts.Count -eq 2) {
    $prefix = Normalize-OuiPrefix $spaceParts[0]
    $vendor = $spaceParts[1].Trim().Trim('"')
    if ($prefix -and $vendor) {
      $vendors[$prefix] = $vendor
      return
    }
  }
}

$dir = Split-Path -Parent $OutputPath
if ($dir -and -not (Test-Path -LiteralPath $dir)) {
  New-Item -ItemType Directory -Path $dir | Out-Null
}

$header = @(
  "# Auto-generated offline OUI vendor mapping",
  "# Generated by: tools/Import-OuiDataset.ps1",
  "# Format: OUI,VENDOR",
  "# OUI is 6 hex digits (first 3 bytes of a MAC)",
  "# Source file: $InputPath",
  ""
)

$body = $vendors.Keys | Sort-Object | ForEach-Object { "$_,$($vendors[$_])" }

$header + $body | Set-Content -LiteralPath $OutputPath -Encoding UTF8

Write-Host "Wrote $($vendors.Count) OUIs to $OutputPath"